name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Start Containers
        run: docker compose up -d --build

      - name: Run Migrations
        run: docker compose exec -T app sh -c "python manage.py migrate"

      - name: Run Tests
        run: docker compose exec -T app sh -c "python manage.py test"

      - name: Run Linter
        run: docker compose exec -T app sh -c "flake8"
